### ISSUE TITLE
Docker on arfmhf (Raspberry Pi) still showing v0.8.0

### ISSUE THREAD

**Issue by scottuf53** [JasonHHouse/gaps#243]
I stopped, removed, deleted the images, and reinstalled from scratch and it is still showing v0.8.0 in the about page.

Steps:
docker stop mygaps
docker rm mygaps
docker image rm 9ac1d6829773
docker pull housewrecker/gaps:armhf-latest
docker stop mygapsdocker run -d -p 8484:8484 --name mygaps -v /{localFolder}/gaps:/usr/data housewrecker/gaps:armhf-latest

I also tried changing /{localFolder} to another location but it still shows v0.8.0

<img width="1115" alt="Screen Shot 2021-06-12 at 10 31 39 AM" src="https://user-images.githubusercontent.com/75382634/121779399-6ddaea00-cb69-11eb-872e-deeae6cc3e8b.png">

**Comment by JasonHHouse** [comment]
Try pulling, it should be updated.

**Comment by scottuf53** [comment]
Did a Docker pull with the command above and it's still reporting 0.8.0

**Comment by JasonHHouse** [comment]
I did some research and it looks like `armhf` is depreciated and `armv6` and `armv7` are recommended. 

I built a new `armv7`, please pull and try that out. `docker pull housewrecker/gaps:arm32v7-latest`

**Comment by scottuf53** [comment]
I got that installed, and the docker will start and run, but the webpage won't load.

**Comment by JasonHHouse** [comment]
I pushed an update and tested and it's working in my local. Can you try again? 

Make sure to stop the other gaps docker image so that port 8484 isn't already bound.

**Comment by scottuf53** [comment]
I still can't get it to load the webpage. You can see the only other dockers I have running.

<img width="1521" alt="Screen Shot 2021-06-14 at 8 52 08 PM" src="https://user-images.githubusercontent.com/75382634/121976732-69255a00-cd52-11eb-8ebb-0592cf370aad.png">

**Comment by JasonHHouse** [comment]
13 seconds is probably not long enough for the JVM to start. On my machine it's 30 seconds to a minute to warm up. You can view the logs to know when Spring starts.

**Comment by scottuf53** [comment]
It's been up for 6 minutes now and still can't load the webpage. I have no idea where to find the logs.

**Comment by JasonHHouse** [comment]
` docker logs [OPTIONS] CONTAINER`

**Comment by scottuf53** [comment]
`pi@raspberrypi:~ $ docker logs mygaps
Enable SSL: false
Enable Login: false
Base URL: 
Jar File: gaps.jar
OpenJDK Server VM warning: No monotonic clock was available - timed services may be adversely affected if the time-of-day clock changes

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::                (v2.5.1)

1930-10-21 10:23:53.982  INFO 8 --- [           main] com.jasonhhouse.gaps.GapsApplication     : Starting GapsApplication v0.9.8 using Java 11.0.11 on a4bce0cb18c6 with PID 8 (/usr/app/gaps.jar started by root in /usr/app)
1970-01-01 00:00:00.000  INFO 8 --- [           main] com.jasonhhouse.gaps.GapsApplication     : The following profiles are active: no-ssl-no-login
1997-08-22 00:06:24.000  WARN 8 --- [           main] o.s.b.c.config.ConfigDataEnvironment     : Property 'spring.profiles' imported from location 'class path resource [application-no-ssl-no-login.yaml]' is invalid and should be replaced with 'spring.config.activate.on-profile' [origin: class path resource [application-no-ssl-no-login.yaml] from gaps.jar - 10:13]
pi@raspberrypi:~ $ 
`

**Comment by JasonHHouse** [comment]
Are you running with docker compose or plain docker?

**Comment by scottuf53** [comment]
Not sure.  I installed with these commands:
curl -fsSL https://get.docker.com -o get-docker.sh
sudo sh get-docker.sh

So whatever that installs. Gaps worked just fine at v0.8.0, but now it's not running.

Here is the docker version output.

pi@raspberrypi:~ $ docker version
Client: Docker Engine - Community
 Version:           20.10.7
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        f0df350
 Built:             Wed Jun  2 11:57:27 2021
 OS/Arch:           linux/arm
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.7
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       b0f5bc3
  Built:            Wed Jun  2 11:55:25 2021
  OS/Arch:          linux/arm
  Experimental:     false
 containerd:
  Version:          1.4.6
  GitCommit:        d71fcd7d8303cbf684402823e425e9dd2e99285d
 runc:
  Version:          1.0.0-rc95
  GitCommit:        b9ee9c6314599f1b4a7f497e1f1f856fe433d3b7
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
pi@raspberrypi:~ $

**Comment by JasonHHouse** [comment]
`docker run -p 8484:8484 --name arm32v7 housewrecker/gaps:arm32v7-latest ` Can you try this?

**Comment by scottuf53** [comment]
Here's the output. It's stuck on the last line, hasn't returned to a prompt yet (maybe that's supposed to happen?).  Webpage still not loading.

```
pi@raspberrypi:~ $ docker run -p 8484:8484 --name arm32v7 housewrecker/gaps:arm32v7-latest
Enable SSL: false
Enable Login: false
Base URL: 
Jar File: gaps.jar
OpenJDK Server VM warning: No monotonic clock was available - timed services may be adversely affected if the time-of-day clock changes

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::                (v2.5.1)

1930-10-22 18:15:22.072  INFO 8 --- [           main] com.jasonhhouse.gaps.GapsApplication     : Starting GapsApplication v0.9.8 using Java 11.0.11 on 1ffb62742ec8 with PID 8 (/usr/app/gaps.jar started by root in /usr/app)
1970-01-01 00:00:00.000  INFO 8 --- [           main] com.jasonhhouse.gaps.GapsApplication     : The following profiles are active: no-ssl-no-login
1997-08-21 22:36:24.000  WARN 8 --- [           main] o.s.b.c.config.ConfigDataEnvironment     : Property 'spring.profiles' imported from location 'class path resource [application-no-ssl-no-login.yaml]' is invalid and should be replaced with 'spring.config.activate.on-profile' [origin: class path resource [application-no-ssl-no-login.yaml] from gaps.jar - 10:13]


```

**Comment by JasonHHouse** [comment]
That's just the first three lines. There should be more to come. What RPI do you have?

`Enable SSL: false
Enable Login: false
Base URL: 
Jar File: gaps.jar

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::                (v2.5.1)

2021-06-15 00:39:19.932  INFO 11 --- [           main] com.jasonhhouse.gaps.GapsApplication     : Starting GapsApplication v0.9.8 using Java 11.0.11 on 54a661bf66f5 with PID 11 (/usr/app/gaps.jar started by root in /usr/app)
2021-06-15 00:39:19.945  INFO 11 --- [           main] com.jasonhhouse.gaps.GapsApplication     : The following profiles are active: no-ssl-no-login
2021-06-15 00:39:20.340  WARN 11 --- [           main] o.s.b.c.config.ConfigDataEnvironment     : Property 'spring.profiles' imported from location 'class path resource [application-no-ssl-no-login.yaml]' is invalid and should be replaced with 'spring.config.activate.on-profile' [origin: class path resource [application-no-ssl-no-login.yaml] from gaps.jar - 10:13]
2021-06-15 00:39:27.048  INFO 11 --- [           main] .s.d.r.c.RepositoryConfigurationDelegate : Bootstrapping Spring Data JPA repositories in DEFAULT mode.
2021-06-15 00:39:27.437  INFO 11 --- [           main] .s.d.r.c.RepositoryConfigurationDelegate : Finished Spring Data repository scanning in 343 ms. Found 1 JPA repository interfaces.
2021-06-15 00:39:31.497  INFO 11 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port(s): 8484 (http)
2021-06-15 00:39:31.609  INFO 11 --- [           main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
2021-06-15 00:39:31.610  INFO 11 --- [           main] org.apache.catalina.core.StandardEngine  : Starting Servlet engine: [Apache Tomcat/9.0.46]
2021-06-15 00:39:31.913  INFO 11 --- [           main] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
2021-06-15 00:39:31.914  INFO 11 --- [           main] w.s.c.ServletWebServerApplicationContext : Root WebApplicationContext: initialization completed in 11569 ms
2021-06-15 00:39:33.328  INFO 11 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Starting...
2021-06-15 00:39:33.702  INFO 11 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Start completed.
2021-06-15 00:39:34.163  INFO 11 --- [           main] o.hibernate.jpa.internal.util.LogHelper  : HHH000204: Processing PersistenceUnitInfo [
	name: default
	...]
2021-06-15 00:39:34.627  INFO 11 --- [           main] org.hibernate.Version                    : HHH000412: Hibernate Core {5.2.12.Final}
2021-06-15 00:39:34.637  INFO 11 --- [           main] org.hibernate.cfg.Environment            : HHH000206: hibernate.properties not found
2021-06-15 00:39:34.891  INFO 11 --- [           main] o.hibernate.annotations.common.Version   : HCANN000001: Hibernate Commons Annotations {5.0.1.Final}
2021-06-15 00:39:34.997  INFO 11 --- [           main] org.hibernate.dialect.Dialect            : HHH000400: Using dialect: org.hibernate.dialect.SQLiteDialect
2021-06-15 00:39:36.055  INFO 11 --- [           main] org.hibernate.dialect.Dialect            : HHH000400: Using dialect: com.jasonhhouse.gaps.sql.SQLDialect
2021-06-15 00:39:36.191  INFO 11 --- [           main] o.h.e.j.e.i.LobCreatorBuilderImpl        : HHH000423: Disabling contextual LOB creation as JDBC driver reported JDBC version [2] less than 4
2021-06-15 00:39:39.308  INFO 11 --- [           main] j.LocalContainerEntityManagerFactoryBean : Initialized JPA EntityManagerFactory for persistence unit 'default'
2021-06-15 00:39:39.958  WARN 11 --- [           main] JpaBaseConfiguration$JpaWebConfiguration : spring.jpa.open-in-view is enabled by default. Therefore, database queries may be performed during view rendering. Explicitly configure spring.jpa.open-in-view to disable this warning
2021-06-15 00:39:43.946  INFO 11 --- [           main] com.jasonhhouse.gaps.RestartMonitor      : init()
2021-06-15 00:39:43.948  INFO 11 --- [           main] c.j.gaps.service.SchedulerService        : getRawSchedule()
2021-06-15 00:39:43.950  WARN 11 --- [           main] c.j.gaps.service.FileIoService           : Can't find json file '/usr/data/gaps.properties'. Most likely first run.
2021-06-15 00:39:43.954  INFO 11 --- [           main] com.jasonhhouse.gaps.RestartMonitor      : Setting saved schedule to cron job
2021-06-15 00:39:43.954  INFO 11 --- [           main] c.j.gaps.service.SchedulerService        : setSchedule( SchedulePayload{schedule=2, enabled=true} )
2021-06-15 00:39:43.957  WARN 11 --- [           main] c.j.gaps.service.FileIoService           : Can't find json file '/usr/data/gaps.properties'. Most likely first run.
2021-06-15 00:39:43.961  INFO 11 --- [           main] c.j.gaps.service.FileIoService           : writeProperties( PlexProperties{plexServers=[], movieDbApiKey='', password='', telegramProperties=TelegramProperties{botId='', chatId='', enabled='false', notificationTypes=[]}, pushBulletProperties=PushBulletProperties{channelTag='', accessToken='', enabled=false, notificationTypes=[]}, emailProperties=EmailProperties{username='', password='', mailTo='', mailFrom='', mailServer='', mailPort=0, mailTransportProtocol='', mailSmtpAuth='', mailSmtpTlsEnabled=false, enabled=false, notificationTypes=[]}, gotifyProperties=GotifyProperties{address='', token='', enabled=false, notificationTypes=[]}, slackProperties=SlackProperties{webHookUrl='', enabled=false, notificationTypes=[]}, pushOverProperties=PushOverProperties{token='', user='', priority=0, sound='', retry=0, expire=0, enabled=false, notificationTypes=[]}, discordProperties=DiscordProperties{webHookUrl=''}, schedule=Schedule{message='Weekly', cron='0 0 4 * * MON', id=2, enabled=true}} )
2021-06-15 00:39:44.576  INFO 11 --- [           main] c.j.gaps.service.SchedulerService        : Setting schedule for Weekly as cron '0 0 4 * * MON'
2021-06-15 00:39:44.577  INFO 11 --- [           main] c.j.gaps.service.SchedulerService        : Cron TimeZone sun.util.calendar.ZoneInfo[id="GMT",offset=0,dstSavings=0,useDaylight=false,transitions=0,lastRule=null]
2021-06-15 00:39:44.997  INFO 11 --- [           main] com.jasonhhouse.gaps.WebSecurityConfig   : userDetailsService()
2021-06-15 00:39:45.321  INFO 11 --- [           main] com.jasonhhouse.gaps.WebSecurityConfig   : Name: Gaps
2021-06-15 00:39:45.321  INFO 11 --- [           main] com.jasonhhouse.gaps.WebSecurityConfig   : Description: Gaps searches through your Plex Server or local folders for all movies, then queries for known movies in the same collection. If those movies don't exist in your library, Gaps will recommend getting those movies, legally of course.
2021-06-15 00:39:45.321  INFO 11 --- [           main] com.jasonhhouse.gaps.WebSecurityConfig   : Version: 0.9.8
2021-06-15 00:39:45.321  INFO 11 --- [           main] com.jasonhhouse.gaps.WebSecurityConfig   : LoginEnabled: false
2021-06-15 00:39:45.334  INFO 11 --- [           main] o.s.s.web.DefaultSecurityFilterChain     : Will secure Ant [pattern='/resources/**'] with []
2021-06-15 00:39:45.335  INFO 11 --- [           main] o.s.s.web.DefaultSecurityFilterChain     : Will secure Ant [pattern='/static/**'] with []
2021-06-15 00:39:45.335  INFO 11 --- [           main] o.s.s.web.DefaultSecurityFilterChain     : Will secure Ant [pattern='/css/**'] with []
2021-06-15 00:39:45.335  INFO 11 --- [           main] o.s.s.web.DefaultSecurityFilterChain     : Will secure Ant [pattern='/js/**'] with []
2021-06-15 00:39:45.336  INFO 11 --- [           main] o.s.s.web.DefaultSecurityFilterChain     : Will secure Ant [pattern='/images/**'] with []
2021-06-15 00:39:46.994  INFO 11 --- [           main] o.s.b.a.w.s.WelcomePageHandlerMapping    : Adding welcome page template: index
2021-06-15 00:39:50.395  INFO 11 --- [           main] o.s.b.a.e.web.EndpointLinksResolver      : Exposing 1 endpoint(s) beneath base path '/actuator'
2021-06-15 00:39:50.458  INFO 11 --- [           main] o.s.s.web.DefaultSecurityFilterChain     : Will secure any request with [org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter@1d65a81, org.springframework.security.web.context.SecurityContextPersistenceFilter@1116ca2, org.springframework.security.web.header.HeaderWriterFilter@1126e26, org.springframework.web.filter.CorsFilter@9cfc77, org.springframework.security.web.authentication.logout.LogoutFilter@b0d1fa, org.springframework.security.web.savedrequest.RequestCacheAwareFilter@13bb809, org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter@240cf2, org.springframework.security.web.authentication.AnonymousAuthenticationFilter@18d76e, org.springframework.security.web.session.SessionManagementFilter@6d2016, org.springframework.security.web.access.ExceptionTranslationFilter@8c5fb3]
2021-06-15 00:39:52.338  INFO 11 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat started on port(s): 8484 (http) with context path ''
2021-06-15 00:39:52.349  INFO 11 --- [           main] o.s.m.s.b.SimpleBrokerMessageHandler     : Starting...
2021-06-15 00:39:52.350  INFO 11 --- [           main] o.s.m.s.b.SimpleBrokerMessageHandler     : BrokerAvailabilityEvent[available=true, SimpleBrokerMessageHandler [org.springframework.messaging.simp.broker.DefaultSubscriptionRegistry@139aac4]]
2021-06-15 00:39:52.351  INFO 11 --- [           main] o.s.m.s.b.SimpleBrokerMessageHandler     : Started.
2021-06-15 00:39:52.437  INFO 11 --- [           main] com.jasonhhouse.gaps.GapsApplication     : Started GapsApplication in 35.607 seconds (JVM running for 39.056)
2021-06-15 00:39:59.994  INFO 11 --- [nio-8484-exec-1] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring DispatcherServlet 'dispatcherServlet'
2021-06-15 00:39:59.995  INFO 11 --- [nio-8484-exec-1] o.s.web.servlet.DispatcherServlet        : Initializing Servlet 'dispatcherServlet'
2021-06-15 00:39:59.999  INFO 11 --- [nio-8484-exec-1] o.s.web.servlet.DispatcherServlet        : Completed initialization in 3 ms
2021-06-15 00:40:00.190  INFO 11 --- [nio-8484-exec-1] c.j.gaps.controller.GapsController       : getIndex()
2021-06-15 00:40:00.429  INFO 11 --- [nio-8484-exec-1] c.j.gaps.controller.GapsController       : initBinder()
2021-06-15 00:40:50.544  INFO 11 --- [MessageBroker-1] o.s.w.s.c.WebSocketMessageBrokerStats    : WebSocketSession[0 current WS(0)-HttpStream(0)-HttpPoll(0), 0 total, 0 closed abnormally (0 connect failure, 0 send limit, 0 transport error)], stompSubProtocol[processed CONNECT(0)-CONNECTED(0)-DISCONNECT(0)], stompBrokerRelay[null], inboundChannel[pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 0], outboundChannel[pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 0], sockJsScheduler[pool size = 1, active threads = 1, queued tasks = 0, completed tasks = 0]
2021-06-15 00:41:02.746  INFO 11 --- [nio-8484-exec-5] c.j.gaps.controller.GapsController       : getIndex()
2021-06-15 00:41:02.752  INFO 11 --- [nio-8484-exec-5] c.j.gaps.controller.GapsController       : initBinder()
2021-06-15 01:10:50.546  INFO 11 --- [MessageBroker-1] o.s.w.s.c.WebSocketMessageBrokerStats    : WebSocketSession[0 current WS(0)-HttpStream(0)-HttpPoll(0), 0 total, 0 closed abnormally (0 connect failure, 0 send limit, 0 transport error)], stompSubProtocol[processed CONNECT(0)-CONNECTED(0)-DISCONNECT(0)], stompBrokerRelay[null], inboundChannel[pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 0], outboundChannel[pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 0], sockJsScheduler[pool size = 2, active threads = 1, queued tasks = 0, completed tasks = 1]
`

**Comment by scottuf53** [comment]
That's all the output. Raspberry Pi 4 Model B - 2 GB.  

<img width="739" alt="Screen Shot 2021-06-14 at 9 32 12 PM" src="https://user-images.githubusercontent.com/75382634/121979400-1e0e4580-cd58-11eb-8fc2-a47672080f89.png">

**Comment by scottuf53** [comment]
And now I can't kill that either
<img width="345" alt="Screen Shot 2021-06-14 at 9 36 39 PM" src="https://user-images.githubusercontent.com/75382634/121979698-abea3080-cd58-11eb-839f-d9729a2ee5c0.png">

**Comment by JasonHHouse** [comment]
Were you able to kill the process? 

In researching more, Spring Boot Docker with RPI can have some issues for some people. I don't have a device to test but I'm wondering if limited memory is the issue.

**Comment by scottuf53** [comment]
Yeah I figured out how to kill it. No big deal, I don't use it a lot, but got notified you updated and that's what prompted all of this. But I don't mind helping test.

**Comment by JasonHHouse** [comment]
Can you try this one?

`docker pull housewrecker/gaps:arm-latest`

**Comment by scottuf53** [comment]
WARNING: The requested image's platform (linux/arm64) does not match the detected host platform (linux/arm/v7) and no specific platform was requested

**Comment by JasonHHouse** [comment]
Gotcha. That confirms you are on ARMv7. Did it still run? Or just stop there?

**Comment by scottuf53** [comment]
It didn't run, just stopped there.

FYI- I'll need to pick this up tomorrow.

**Comment by JasonHHouse** [comment]
Okay, I'll keep poking around.
